### ISSUE TITLE
 No such file or directory: 'input/valid/meta_expressions.json'

### ISSUE THREAD

**Issue by Sillyyk** [Tapall-AI/MeViS_Track_Solution_2024#1]
may i ask  what is placed in ”--mevis_path “, is it an input address？and why is this error reported？

**Comment by gaomingqi** [comment]
Hello, the argument "--mevis_path" should be followed by the root path of MeViS. From the error reported, I think you run the command like this: "--mevis_path input", where you should make sure the path 'input' is the root path of MeViS.

**Comment by gaomingqi** [comment]
Hello, the argument "--mevis_path" should be followed by the root path of MeViS. From the error reported, I think you run the command like this: "--mevis_path input", where you should make sure the path 'input' is the root path of MeViS.

MeViS data is organised as follows:
```
MeViS/        # root path
└── train
        └── JPEGImages
        └── mask_dict.json
        └── meta_expressions.json
└── valid
        └── JPEGImages
        └── meta_expressions.json
└── valid_u
        └── JPEGImages
        └── mask_dict.json
        └── meta_expressions.json
└── test
        └── JPEGImages
        └── meta_expressions.json
```

**Comment by gaomingqi** [comment]
Hello, the argument "--mevis_path" should be assigned as the root path of MeViS. From the error reported, I think you run the command like this: "--mevis_path input", where you should make sure the path 'input' is the root path of MeViS.

MeViS data is organised as follows:
```
MeViS/        # root path
└── train
        └── JPEGImages
        └── mask_dict.json
        └── meta_expressions.json
└── valid
        └── JPEGImages
        └── meta_expressions.json
└── valid_u
        └── JPEGImages
        └── mask_dict.json
        └── meta_expressions.json
└── test
        └── JPEGImages
        └── meta_expressions.json
```

**Comment by gaomingqi** [comment]
Hello, the argument "--mevis_path" should be assigned as the root path of MeViS. From the error reported, I think you ran the command like this: "--mevis_path input", where you should make sure 'input' is the root path of MeViS.

MeViS data is organised as follows:
```
MeViS/        # root path
└── train
        └── JPEGImages/
        └── mask_dict.json
        └── meta_expressions.json
└── valid
        └── JPEGImages/
        └── meta_expressions.json
└── valid_u
        └── JPEGImages/
        └── mask_dict.json
        └── meta_expressions.json
└── test
        └── JPEGImages/
        └── meta_expressions.json
```
