### ISSUE TITLE
How many GPU do you use?

### ISSUE THREAD

**Issue by tranxuantuyen** [Tapall-AI/MeViS_Track_Solution_2024#2]
Hi, how many GPU do you use to finetune MeVis. I see in the command line you set number of GPU = 1. Are all parameters extractly the same as when you train the model to win challange? Thank you

**Comment by tranxuantuyen** [comment]
Btw, I encountered an `out of memory` error when training this model. What type of GPU (A100 or V100) did you use to train it?"

**Comment by gaomingqi** [comment]
Hello, we used 4 a6000 GPUs to fine-tune the model and all other parameters provided are the same as we used during the challenge.
